apiVersion: v1
kind: Pod
metadata:
  name: server-pod-paymentservice
  labels:
    name: server-pod-paymentservice
    app: cluster-1

spec:
  containers:
    - name: server-pod-paymentservice
      image: dilmika4172/cluster-1
      ports:
        - containerPort: 5000
