apiVersion: v1
kind: Service
metadata:
  name: server-pod-paymentservice
  labels:
    name: server-pod-paymentservice
    app: cluster-1

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    name: server-pod-paymentservice
    app: cluster-1
