apiVersion: v1
kind: Pod
metadata:
  name: server-payment-pod
  labels:
    name: server-payment-pod
    app: cluster-1

spec:
  containers:
    - name: server-payment-pod
      image: dilmika4172/cluster-1
      ports:
        - containerPort: 5000
